### ISSUE TITLE
cannot read property 'configureProvider' of undefined

### ISSUE THREAD

**Issue by SamMatthewsIsACommonName** [fullstackreact/react-native-oauth#37]
Hi, as I made reference to here https://github.com/fullstackreact/react-native-oauth/issues/14 
I'm having an issue with the oath on Android. Do I need to configure the manager differently based on platform? At present my code looks like this 
````
const manager = new OAuthManager('MyAPp');
const config = {
  facebook: {
    client_id: 'MY_CLIENT_ID',
    client_secret: 'MY_CLIENT_SECRET',
  },
};
manager.configure(config);
````
It works amazingly (Thanks @auser !!) on ios, but in android everything about the manager is then coming up as undefined. I removed all my promises handling etc to just strip it back to console logging the manager variable but I was getting 'cannot read property 'configureProvider' of undefined and it wouldn't go any further.

Is this a bug or is this just user error? I (think) I;ve read the docs quite extensively and everything seems as it's supposed to be? Cheers

**Comment by SamMatthewsIsACommonName** [comment]
I just realised I hadn't configured anything here. Does this need to be setup or is that only to handle the ios side? If so what values should I put in, is it similar to how the ios is setup? I can't find anything about it in the docs sorry :/
<img width="894" alt="screen shot 2017-01-11 at 20 34 01" src="https://cloud.githubusercontent.com/assets/21329063/21839610/7ded5b54-d83d-11e6-9709-ea0f94cd583c.png">

**Comment by auser** [comment]
Interesting... it should be handled in Android... I just confirmed it's working on android here. What version of `rn-oauth` do you have?

**Comment by auser** [comment]
I just pushed an update. Also, the method name is `authorize`, not `authorise`

**Comment by SamMatthewsIsACommonName** [comment]
I just updated to version 2.19, yeah sorry 'authorise' was a typo here it was authorize.
I'm still getting the error. I've moved the function call and setup to a componentWillMount just so there's no additional factors to consider and it works fine on ios but on android I get this:
````
TypeError: Cannot read property 'authorize' of undefined
    at promisify.js:11
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
    at promisify.js:6
    at OAuthManager.authorize (react-native-oauth.js:38)
    at AppNavigator.componentWillMount (appNavigator.js:48)
    at ReactCompositeComponent.js:347
    at measureLifeCyclePerf (ReactCompositeComponent.js:74)
    at ReactCompositeComponentWrapper.performInitialMount 
````

**Comment by auser** [comment]
What's the difference between your implementation and this? Is there any? https://github.com/fullstackreact/FirestackApp/blob/master/app/views/Authentication/Demos/Providers.js#L38

**Comment by SamMatthewsIsACommonName** [comment]
Here is the implementation along with the accompanying console logs when just fired in a componentWillMount lifecycle method:

````
  componentWillMount() {
    const manager = new OAuthManager('MY_APP');
    const config = {
      facebook: {
        client_id: 'MY_ID',
        client_secret: 'MY_SECRET',
      },
    };
    manager.configure(config);
    console.log('manager:', manager);
    manager.authorize('facebook')
    .then(x => console.log(x))
    .catch(err => console.log('error', err));
  }
````
And the logs:
![screen shot 2017-01-12 at 15](https://cloud.githubusercontent.com/assets/21329063/21874914/f1a78f16-d8dc-11e6-848c-32adf99bb4ab.jpg)

As I said it works fine on ios that's the strange thing, but with android it's not even getting past the fire the function stage

**Comment by SamMatthewsIsACommonName** [comment]
Also you're passing in provider as a variable to authorize but it equals the string  'facebook' in one case so I can't see any difference there

**Comment by auser** [comment]
Can you relink the library? Rnpm unlink and react-native link? It sounds like the android side didn't get linked

**Comment by SamMatthewsIsACommonName** [comment]
On trying to do that it seems my folder structure isn't quite what link is expecting, I've pmed you on gitter with the details, not sure if it's expected behaviour or my project is set up wrong?

**Comment by auser** [comment]
Responded

**Comment by signorekai** [comment]
I am also encountering this same issue, and react-native unlink then react-native link didn't solve the issue. Any idea?

**Comment by SamMatthewsIsACommonName** [comment]
Hi @signorekai does your android package name end in com.android by any chance? This was causing a problem with link for me

**Comment by signorekai** [comment]
No it didn't, unfortunately.

**Comment by auser** [comment]
Happy to hop on ScreenHero to help debug.

**Comment by tendolukwago** [comment]
Hi @auser , I'm having the same issue on iOS. I tried the react-native unlink and react-native link, as well and that didn't resolve the issue. I took a look at the set up you have in the link and nothing glaringly different. Here's how I'm 

`
componentWillMount(){
        const manager = new OAuthManager('my_app_name');

        const config =  {
            twitter: {
                consumer_key: 'my_consumer_key',
                consumer_secret: 'my_consumer_secret'
            },
            facebook: {
                client_id: 'my_client_id',
                client_secret: 'my_client_secret'
            }
        };
        manager.configure(config);
	this.manager = manager;
}
`

**Comment by jsbranco** [comment]
Also having this issue.. @tendolukwago/ @SamMatthewsIsACommonName   did you manage to resolve this ?

**Comment by tendolukwago** [comment]
@jsbranco  Not yet. The functionality wasn't pertinent at the time of posting this message, but is more pressing now. I'll be taking a look at it again this weekend, and will follow up.

**Comment by jsbranco** [comment]
@tendolukwago sure let me know if there is anything I can help with

**Comment by ozsirma** [comment]
I have the same problem in iOS. 

<img width="1206" alt="react_native_debugger" src="https://cloud.githubusercontent.com/assets/17460410/23462502/b806731e-fe96-11e6-9509-cd265b277c17.png">

**Comment by ozsirma** [comment]
Is there any progress ?

**Comment by jsbranco** [comment]
I have resolved my issue by doing the following changing the key sharing group to : io.fullstack.oauth.AUTH_MANAGER as described in README, i assumed it was my apps's details... but seems like after updating to  this and rebuilding resolved the configureProvider issue.

**Comment by vinhtq** [comment]
I have same issue like @ozsirma

**Comment by jvorcak** [comment]
Did anyone managed to get this running? I've strictly followed the README file, I've added `io.fullstack.oauth.AUTH_MANAGER` as Keychain Sharing group. I've run `react-native link` and I still get this error, even in a new project.

**Comment by jvorcak** [comment]
Ok I've figured it out. For me I haven't noticed `Next, navigate to the neighboring "Build Phases" section of project settings, find the "Link Binary with Library" drop down, expand it, and click the "+" to add libOAuthManager.a to the list.` in README. 

I'm relatively new to react-native, but is there any reason why `react-native link` can't do this for us @auser ? Maybe if we discuss this I could help out and learn how automatic linking works.

**Comment by DmitryMaksakov** [comment]
I have the same error. Have anyone found a solution?

**Comment by nickcobbett** [comment]
I'm having the same problem iOS. Has this been resolved?

**Comment by kodie** [comment]
Running into this issue too on iOS and I really need to get this working. :/

**Comment by kodie** [comment]
@auser Any ideas? Only running into this issue on iOS. I've gone through the setup instructions multiple times. Working fine on Android other than running into #158

**Comment by ydvsailendar** [comment]
i am getting the same issue in android. can you please help. @kodie looks like your setup worked fine in android as you have mentioned. i am new to this and looking please help. i need this to work as soon as possible. Thank you.
